version: "3"
networks:
    mynetwork:
services:
    web:
        build: ./project
        networks:
            - mynetwork 
        container_name: web
        environment:
            - MODELNAME=model_FT.bin
        expose:
            - "5000"
        ports:
            - "5000:5000"
        volumes:
            - ./models:/opt/fastText
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: query_results_db
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./dbDir:/var/lib/postgresql/data
        expose:
            - "5432"
        ports:
            - "5432:5432"
